<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>SpaceX</title>';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<!--<link rel="stylesheet" href="css/utilities.css">-->';
echo '<script src="js/script.js"></script>';
echo '</head>';
echo '<body>';
echo '<!-- Content goes here -->';
echo '<div id="overlay"></div>';
echo '<div id="mobile-menu" class="mobile-main-menu"><!-- mobile menu -->';
echo '<ul>';
echo '<li><a href="#">Mission</a></li>';
echo '<li><a href="#">Launches</a></li>';
echo '<li><a href="#">Careers</a></li>';
echo '<li><a href="#">Updates</a></li>';
echo '<li><a href="#">Shop</a></li>';
echo '';
echo '<li class="mobile-only"><a href="falcon9.html">Falcon 9</a></li>';
echo '<li class="mobile-only"><a href="falcon-heavy.html">Falcon Heavy</a></li>';
echo '<li class="mobile-only"><a href="dragon.html">Dragon</a></li>';
echo '<li class="mobile-only"><a href="#">Starship</a></li>';
echo '<li class="mobile-only"><a href="#">Human Spaceflight</a></li>';
echo '<li class="mobile-only"><a href="#">Rideshare</a></li>';
echo '<li class="mobile-only"><a href="#">Starlink</a></li>';
echo '</ul>';
echo '</div>';
echo '<header class="main-header"><!-- main header -->';
echo '<div class="logo">';
echo '<a href="index.html">';
echo '<img src="images/logo.png" alt="physalislabs" />';
echo '</a>';
echo '</div>';
echo '<nav class="desktop-main-menu">';
echo '<ul>';
echo '<li class="active"><a href="kenjix1.html">Kenji X1</a></li>';
echo '<li><a href="geo-lab.html">Geo-Lab</a></li>';
echo '<li><a href="dragon.html">Dragon</a></li>';
echo '<li><a href="#">Starship</a></li>';
echo '<li><a href="#">Human Spaceflight</a></li>';
echo '<li><a href="#">Rideshare</a></li>';
echo '<li><a href="#">Starlink</a></li>';
echo '<li><a href="#">Shop</a></li>';
echo '</ul>';
echo '</nav>';
echo '</header>';
echo '';
echo '<!-- Hamburger Menu -->';
echo '<button id="menu-btn" class="hamburger" type="button">';
echo '<span class="hamburger-top"></span>';
echo '<span class="hamburger-middle"></span>';
echo '<span class="hamburger-bottom"></span>';
echo '</button>';
echo '';
echo '';
echo '';
echo '';
echo '<!-- Section A -->';
echo '<section class="section-a">';
echo '<div class="section-inner">';
echo '<h4>Upcoming Launch</h4>';
echo '<h2>CRS-25 Mission</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '<div class="scroll-arrow">';
echo '<svg width="30px" height="20px">';
echo '<path stroke="#ffffff" fill="none" stroke-width="2px" d="M2.000,5.000 L15.000,18.000 L28.000,5.000"></path>';
echo '</svg>';
echo '</div>';
echo '<!-- try to add and astronaut -->';
echo '<div class="astronaut">';
echo '<img src="./images/astronaut.png" alt="astronaut">';
echo '</div>';
echo '</section>';
echo '<!-- Section B -->';
echo '<section class="section-b">';
echo '<div class="section-inner">';
echo '<h4>Recent Launch</h4>';
echo '<h2>Stralink Mission</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '<div class="scroll-arrow">';
echo '<svg width="30px" height="20px">';
echo '<path stroke="#ffffff" fill="none" stroke-width="2px" d="M2.000,5.000 L15.000,18.000 L28.000,5.000"></path>';
echo '</svg>';
echo '</div>';
echo '</section>';
echo '<!-- Section C -->';
echo '<section class="section-c">';
echo '<div class="section-inner">';
echo '<h4>Recent Mission</h4>';
echo '<h2>SES-22 Mission</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '<div class="scroll-arrow">';
echo '<svg width="30px" height="20px">';
echo '<path stroke="#ffffff" fill="none" stroke-width="2px" d="M2.000,5.000 L15.000,18.000 L28.000,5.000"></path>';
echo '</svg>';
echo '</div>';
echo '</section>';
echo '<!-- Section D -->';
echo '<section class="section-d">';
echo '<div class="section-inner">';
echo '<h4>Recent Launch</h4>';
echo '<h2>Globalstar FM-15 Mission</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '<div class="scroll-arrow">';
echo '<svg width="30px" height="20px">';
echo '<path stroke="#ffffff" fill="none" stroke-width="2px" d="M2.000,5.000 L15.000,18.000 L28.000,5.000"></path>';
echo '</svg>';
echo '</div>';
echo '</section>';
echo '<!-- Section E -->';
echo '<section class="section-e">';
echo '<div class="section-inner">';
echo '<h2>Starship Update</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '<div class="scroll-arrow">';
echo '<svg width="30px" height="20px">';
echo '<path stroke="#ffffff" fill="none" stroke-width="2px" d="M2.000,5.000 L15.000,18.000 L28.000,5.000"></path>';
echo '</svg>';
echo '</div>';
echo '</section>';
echo '<!-- Section F -->';
echo '<section class="section-f">';
echo '<div class="section-inner">';
echo '<h2>Starship to add NASA astronaut on the moon</h2>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Rewatch</span>';
echo '</a>';
echo '</div>';
echo '</section>';
echo '<!-- Join us -->';
echo '<section class="strip">';
echo '<h3>Physalis labs</h3>';
echo '<a href="#" class="btn">';
echo '<div class="hover"></div>';
echo '<span>Join now</span>';
echo '</a>';
echo '</section>';
echo '';
echo '<!-- Footer -->';
echo '<footer>';
echo '<ul>';
echo '<li>physalislabs &copy; 2023</li>';
echo '<li><a href="https://www.linkedin.com/company/physalis-labs/" target="_blank">Linkedin</a></li>';
echo '<li><a href="https://www.youtube.com/@physalislabs9881" target="_blank">YouTube</a></li>';
echo '<!--<li><a href="#">Instagram</a></li>';
echo '<li><a href="#">FLickr</a></li>';
echo '<li><a href="#">LinkedIn</a></li>';
echo '<li><a href="#">Privacy</a></li>';
echo '<li><a href="#">Suppliers</a></li>-->';
echo '<ul>';
echo '</footer>';
echo '';
echo '</body>';
echo '</html>';
echo '<!--<script src="js/script.js"></script>--><!-- Script placement: Ensure that your JavaScript code is placed after the HTML element or after the DOM (Document Object Model) has loaded. Placing the script in the <head> section without any waiting mechanism may cause the code to execute before the element is available in the DOM. -->';
?>